auto_resume: true
backend: nccl
cache_dir: null
config: ./downstream/sv_voxceleb1/config.yaml
device: cuda
downstream: sv_voxceleb1
downstream_variant: null
evaluate_split: test
expdir: result/downstream/ws/sv/hubert_1e-4
expname: null
init_ckpt: null
local_rank: null
mode: train
override: config.optimizer.lr=1.0e-4
past_exp: null
seed: 1337
upstream: hubert
upstream_ckpt: null
upstream_feature_selection: hidden_states
upstream_model_config: null
upstream_refresh: false
upstream_trainable: false
verbose: false
