auto_resume: true
backend: nccl
cache_dir: null
config: ./downstream/asr/config.yaml
device: cuda
downstream: asr
downstream_variant: null
evaluate_split: test
expdir: result/downstream/asr/new_interface/repro_s3prl_base_v2
expname: null
init_ckpt: result/downstream/asr/new_interface/repro_s3prl_base_v2/states-153500.ckpt
local_rank: null
mode: train
override: null
past_exp: result/downstream/asr/new_interface/repro_s3prl_base_v2
seed: 1337
upstream: wav2vec2_base_960
upstream_ckpt: null
upstream_feature_selection: hidden_states
upstream_model_config: null
upstream_refresh: false
upstream_trainable: false
verbose: false
